"""Add template_id

Revision ID: 2ba5b07db6a7
Revises: 5f298944a3ec
Create Date: 2026-09-08 22:08:49.621637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba5b07db6a7'
down_revision: Union[str, Sequence[str], None] = '5f298944a3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_logs', sa.Column('template_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'campaign_logs', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign_logs', type_='foreignkey')
    op.drop_column('campaign_logs', 'template_id')
    # ### end Alembic commands ###
